/**
 * Call State Machine
 * Represents the complete lifecycle of an AI phone call
 */
export enum CallState {
  IDLE = 'IDLE',
  QUEUED = 'QUEUED',
  INITIALIZING = 'INITIALIZING',
  DIALING = 'DIALING',
  RINGING = 'RINGING',
  CONNECTED = 'CONNECTED',
  GREETING = 'GREETING',
  LISTENING = 'LISTENING',
  PROCESSING = 'PROCESSING',
  GENERATING_RESPONSE = 'GENERATING_RESPONSE',
  PLAYING_RESPONSE = 'PLAYING_RESPONSE',
  WAITING = 'WAITING',
  CONTINUING = 'CONTINUING',
  ENDING = 'ENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRY = 'RETRY',
}

/**
 * Campaign Execution State
 */
export enum CampaignState {
  IDLE = 'IDLE',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

/**
 * Conversation State
 */
export enum ConversationState {
  INITIALIZING = 'INITIALIZING',
  GREETING = 'GREETING',
  ACTIVE = 'ACTIVE',
  LISTENING = 'LISTENING',
  THINKING = 'THINKING',
  RESPONDING = 'RESPONDING',
  WAITING_FOR_INPUT = 'WAITING_FOR_INPUT',
  HANDLING_INTERRUPTION = 'HANDLING_INTERRUPTION',
  HANDLING_SILENCE = 'HANDLING_SILENCE',
  CONTEXT_SWITCHING = 'CONTEXT_SWITCHING',
  CLOSING = 'CLOSING',
  ENDED = 'ENDED',
}

/**
 * Pipeline Event Types
 */
export enum PipelineEvent {
  CAMPAIGN_STARTED = 'CAMPAIGN_STARTED',
  CONTACT_LOADED = 'CONTACT_LOADED',
  CALL_STARTED = 'CALL_STARTED',
  CALL_CONNECTED = 'CALL_CONNECTED',
  CUSTOMER_SPEAKING = 'CUSTOMER_SPEAKING',
  SPEECH_RECOGNIZED = 'SPEECH_RECOGNIZED',
  KNOWLEDGE_RETRIEVED = 'KNOWLEDGE_RETRIEVED',
  PROMPT_GENERATED = 'PROMPT_GENERATED',
  RESPONSE_GENERATED = 'RESPONSE_GENERATED',
  AUDIO_GENERATED = 'AUDIO_GENERATED',
  AUDIO_PLAYED = 'AUDIO_PLAYED',
  MEMORY_UPDATED = 'MEMORY_UPDATED',
  TRANSCRIPT_UPDATED = 'TRANSCRIPT_UPDATED',
  RECORDING_SAVED = 'RECORDING_SAVED',
  CALL_COMPLETED = 'CALL_COMPLETED',
  CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED',
  ERROR_OCCURRED = 'ERROR_OCCURRED',
}

/**
 * Call Direction
 */
export enum CallDirection {
  OUTBOUND = 'OUTBOUND',
  INBOUND = 'INBOUND',
}

/**
 * Call Result
 */
export enum CallResult {
  SUCCESS = 'SUCCESS',
  NO_ANSWER = 'NO_ANSWER',
  BUSY = 'BUSY',
  FAILED = 'FAILED',
  VOICEMAIL = 'VOICEMAIL',
  REJECTED = 'REJECTED',
  ERROR = 'ERROR',
}
